use trncentre_adv_v7
go





DROP TABLE DBO.CADASTRO
GO

DROP TABLE DBO.LOGRADOURO
GO

DROP TABLE DBO.CARTAO
GO

drop table EXTRATO
go

drop table FATURA
go



CREATE TABLE DBO.CADASTRO (
	CPF_USUARIO CHAR(11) primary key not null
,	SENHA_USUARIO VARCHAR(50) not null
,	Tel_Fixo varchar(12)
,	Tel_Cel varchar(12) not null
,	Nome varchar(20) not null
,	Sobrenome varchar(50) not null
,	EMAIL VARCHAR(50) NOT NULL

)


CREATE TABLE DBO.LOGRADOURO
(
	CPF_USUARIO CHAR(11) NOT NULL
,	ENDERECO VARCHAR(30) NOT NULL
,	CIDADE   VARCHAR(15) NOT NULL
,	ESTADO	CHAR(2) NOT NULL
,	BAIRRO VARCHAR(20) NOT NULL
,	CEP    CHAR(8) NOT NULL
,	COMPLEMENTO VARCHAR(15) 
)


CREATE TABLE DBO.CARTAO
(
	CPF_USUARIO CHAR(11) NOT NULL
,	NUMERO_CARTAO BIGINT NOT NULL
,	DATA_VALIDADE DATE NOT NULL
,	COD_SEGURACA CHAR(3) NOT NULL
)


CREATE TABLE DBO.EXTRATO
(
	NUMERO_CARTAO BIGINT NOT NULL
,	DESCRICAO_COMPRA VARCHAR(20)  NOT NULL
,	DATA_COMPRA DATETIME  NOT NULL
,	VALOR_COMPRA NUMERIC(8,2) NOT NULL
,	STATUS_EXTRATO	CHAR(7) NOT NULL /*DEBITO OU CREDITO*/
)


CREATE TABLE DBO.FATURA
(
	NUMERO_CARTAO BIGINT NOT NULL
,	VALOR_FATURA NUMERIC(8,2) NOT NULL
,	LIMITE_DISPONIVEL NUMERIC(8,2) NOT NULL
,	LIMITE NUMERIC(8,2) NOT NULL
,	DATA_VENCIMENTO DATE not null
,   STATUS_FATURA char(1) not null /*A = paga | P = Pendente || Vencida */
,   Data_Pagamento date not null
)


ALTER TABLE DBO.LOGRADOURO
   ADD CONSTRAINT PK_LOGRADOURO_CPF_USUARIO_CEP PRIMARY KEY CLUSTERED (CPF_USUARIO, CEP);

ALTER TABLE DBO.LOGRADOURO ADD CONSTRAINT FK_Logradouro_cadastro_CPF_Usuario
    FOREIGN KEY (CPF_USUARIO)
    REFERENCES DBO.CADASTRO (CPF_USUARIO)
    ON DELETE CASCADE;


ALTER TABLE DBO.CARTAO
   ADD CONSTRAINT PK_CARTAO_NUMERO_CARTAO_CPF_USUARIO PRIMARY KEY CLUSTERED (NUMERO_CARTAO, CPF_USUARIO);


--ALTER TABLE DBO.EXTRATO
--   ADD CONSTRAINT PK_EXTRATO_NUMERO_CARTAO PRIMARY KEY CLUSTERED (NUMERO_CARTAO);

ALTER TABLE DBO.FATURA
   ADD CONSTRAINT PK_FATURA_NUMERO_CARTAO PRIMARY KEY CLUSTERED (NUMERO_CARTAO,DATA_VENCIMENTO);

ALTER TABLE DBO.FATURA
  ADD CONSTRAINT DF_FATURA_STATUS_FATURA
  DEFAULT ('P') FOR STATUS_FATURA;

--ALTER TABLE DBO.FATURA ADD CONSTRAINT FK_FATURA_EXTRATO_NUMERO_CARTAO
--    FOREIGN KEY (NUMERO_CARTAO)
--    REFERENCES EXTRATO (NUMERO_CARTAO)


